ifndef OM_ROOT
  OM_ROOT = ../..
endif

export OM_ROOT

# MODEL_NAME = $(CUR_SUBDIR)
# SCENARIO_NAME = Default
# OMC_SCENARIO_PARAM_DIR = parameters/$(SCENARIO_NAME)
# OMC_FIXED_PARAM_DIR = parameters/Fixed

include $(OM_ROOT)/models/makefile.model.mak

