// ModelOne: generated by openM++ compiler
// Copyright (c) 2013-2014 OpenM++
// This code is licensed under MIT license (see LICENSE.txt for details)

#include "modelOne_om.h"
using namespace openm;

// model parameters
static const int ageSize = 4;
static const int sexSize = 2;
static const int salarySize = 3;

static int startSeed = 1;
static double ageSex[ageSize][sexSize];
static int salaryAge[salarySize][ageSize];

// model output tables: subsample accumulators
static double salarySexSum[salarySize][sexSize];
static double salarySexCount[salarySize][sexSize];

// Model event loop: user code
void RunModel(IModel * i_model)
{
    theLog->logMsg("Running Simulation");

    // prototype only
    for (int nSalary = 0; nSalary < salarySize; nSalary++) {
        for (int nSex = 0; nSex < sexSize; nSex++) {

            salarySexCount[nSalary][nSex] = (double)(nSalary + nSex + i_model->subSampleNumber() + 1);

            salarySexSum[nSalary][nSex] = 0.0;
            for (int nAge = 0; nAge < ageSize; nAge++) {
                salarySexSum[nSalary][nSex] += 
                    ((double)salaryAge[nSalary][nAge]) * ageSex[nAge][nSex] * (double)(i_model->subSampleNumber() + 1);
            }
        }
    }
}

// Model startup method: initialize parameters
void ModelStartup(IModel * i_model)
{
    // load model parameters
    theLog->logMsg("Reading Parameters");
    i_model->readParameter("StartingSeed", typeid(int), 1, &startSeed);
    i_model->readParameter("ageSex", typeid(double), ageSize * sexSize, ageSex);
    i_model->readParameter("salaryAge", typeid(int),  salarySize * ageSize, salaryAge);
}

// Model shutdown method: write output tables
void ModelShutdown(openm::IModel * i_model)
{
    // write output result tables: salarySex sub-sample
    theLog->logMsg("Writing Output Tables");

    const double * salarySexAccArr[2];
    salarySexAccArr[0] = (double *)salarySexSum;
    salarySexAccArr[1] = (double *)salarySexCount;
    i_model->writeOutputTable("salarySex", 2, salarySize * sexSize, salarySexAccArr);
}
