// ModelOne: generated by openM++ compiler
// Copyright (c) 2013 OpenM++
// This code is licensed under MIT license (see LICENSE.txt for details)

#ifndef MODEL_ONE_H
#define MODEL_ONE_H

using namespace std;

#include "libopenm/omModel.h"

// Model startup method: initialize parameters
void ModelStartup(openm::IModel * i_model);

// Model event loop: user code
void RunModel(openm::IModel * i_model);

// Model shutdown method: write output tables
void ModelShutdown(openm::IModel * i_model);

#endif  // MODEL_ONE_H
