
/**
 * @file   om_types0.h
 * Fundamental Types for model 'Alpha2' - Generated by openM++ compiler
 *  
 *  Model version = 1.0.0.0
 *  Time stamp = _201401220900000377_
 */


#pragma once

namespace mm {
    // fundamental types
    typedef  unsigned int uint;
    typedef  unsigned char uchar;
    typedef  unsigned short ushort;
    typedef  unsigned long ulong;
    typedef  int integer;
    typedef  int counter;
    typedef  double real;
    typedef  double Time;
    typedef double TIME; // for Modgen models
    extern const Time time_infinite;
    extern const Time TIME_INFINITE; // for Modgen models


} // namespace mm
