// ModelOne: generated by openM++ compiler
// Copyright (c) 2013-2015 OpenM++
// This code is licensed under MIT license (see LICENSE.txt for details)

#include "modelOne_om.h"
using namespace openm;

// model name
const char * OM_MODEL_NAME = "modelOne";

// model timestamp: compilation date-time
const char * OM_MODEL_TIMESTAMP = "_201208171604590148_";

namespace openm
{
    // model API entries holder
    struct ModelEntryHolder
    {
        ModelEntryHolder(
            OM_RUN_INIT_HANDLER i_RunInitHandler,
            OM_STARTUP_HANDLER i_ModelStartupHandler,
            OM_EVENT_LOOP_HANDLER i_RunModelHandler,
            OM_SHUTDOWN_HANDLER i_ModelShutdownHandler
            ) 
        { 
            RunInitHandler = i_RunInitHandler;              // link run init function
            ModelStartupHandler = i_ModelStartupHandler;    // link model startup function
            RunModelHandler = i_RunModelHandler;            // link user portion of model event loop
            ModelShutdownHandler = i_ModelShutdownHandler;  // link model shutdown function
        }
    };

    // set entry points to the code generated by openM++ compiler
    static ModelEntryHolder theModelEntry(RunInit, ModelStartup, RunModel, ModelShutdown);
}

