// ModelOne: generated by openM++ compiler
// Copyright (c) 2013-2014 OpenM++
// This code is licensed under MIT license (see LICENSE.txt for details)

#ifndef MODEL_ONE_H
#define MODEL_ONE_H

using namespace std;

#include "libopenm/omModel.h"

// Model run initialization: read input parameters
void RunInit(openm::IRunInit * const i_runInit);

// Model startup method: initialize subsample
void ModelStartup(openm::IModel * const i_model);

// Model event loop: user code
void RunModel(openm::IModel * const i_model);

// Model shutdown method: write output tables
void ModelShutdown(openm::IModel * const i_model);

#endif  // MODEL_ONE_H
