/**
* @file    omPch.h
* Model-independent includes for pre-compiled header
* 
* The file is included first in C++ files generated by the OpenM++ compiler.
*/
// Copyright (c) 2013-2015 OpenM++
// This code is licensed under the MIT license (see LICENSE.txt for details)

#pragma once
