/**
* @file    omPch.h
* Model-independent includes for pre-compiled header
* 
* The file is included first in C++ files generated by the OpenM++ compiler.
* 
* To activate the use of pre-compiled headers in Windows using the Microsoft CL compiler,
* set the property PCH_USE to 1 in the build environment.
*/
// Copyright (c) 2013-2015 OpenM++
// This code is licensed under the MIT license (see LICENSE.txt for details)

#pragma once

// The following line creates a model-dependent pch file which includes all headers.
//#include "omc/omSimulation.h"

// To use only model-invariant headers in the pch file, e.g. from std, #include them here.
