/**
* @file    omSimulation.h
* Common declarations for all models.
* 
* The file is #include'd by the C++ files generated by the OpenM++ compiler.
*/
// Copyright (c) 2013-2015 OpenM++
// This code is licensed under MIT license (see LICENSE.txt for details)

#pragma once
#include <cfloat>
#include <cmath>
#include <cstdarg>
#include "libopenm/omModel.h"

#include "om_types0.h" // fundamental model types
#include "omc/link.h"
#include "omc/Range.h"
#include "omc/Agent.h"
#include "omc/AgentVar.h"
#include "omc/Event.h"
#include "omc/Multilink.h"
#include "omc/EntitySet.h"
#include "omc/cumrate.h"
#include "om_types1.h" // model-specific types

#include "omc/macros.h"
#include "omc/globals.h"

#include "om_declarations.h" // model-specific classes

namespace openm {

    /**
     * model API entries holder.
     * 
     * Used to bind model-specific functions to OpenM++ code which manages the life-cycle of model
     * execution.  The 4 global 'Handler' functions are defined in the framework module used by the
     * model, e.g. use/case_based_modgen.ompp.
     */
    struct ModelEntryHolder
    {
        ModelEntryHolder(
        OM_RUN_INIT_HANDLER i_RunInitHandler,
        OM_STARTUP_HANDLER i_ModelStartupHandler,
        OM_EVENT_LOOP_HANDLER i_RunModelHandler,
        OM_SHUTDOWN_HANDLER i_ModelShutdownHandler
        )
        {
            ::RunInitHandler = i_RunInitHandler;              // link run init function
            ::ModelStartupHandler = i_ModelStartupHandler;    // link model startup function
            ::RunModelHandler = i_RunModelHandler;            // link user portion of model event loop
            ::ModelShutdownHandler = i_ModelShutdownHandler;  // link model shutdown function
        }
    };
}

