#!/usr/bin/env bash
#
# build openM++ UI

# push into ompp root and make log directory if not exist

if [ ! -d ompp ]; then
  echo ERROR: missing source code directory: ompp
  exit 1
fi

pushd ompp
OM_ROOT=$PWD

if [ ! -d log ]; then mkdir log; fi

# log build environment 

echo Log file: log/build-ui.log
echo `date` Build openM++ UI alpha | tee log/build-ui.log 
echo " OM_ROOT = $OM_ROOT" | tee -a log/build-ui.log 

# build openM++ UI: node, npm, vue.js

pushd ompp-ui

do_npm_cmd()
{
  echo npm $@ | tee -a ../log/build-ui.log
  
  if ! npm $@ >> ../log/build-ui.log 2>&1;
  then
    echo FAILED. | tee -a ../log/build-ui.log
    exit 1
  fi
}

export npm_config_cache=$OM_ROOT/build/npm-cache

do_npm_cmd install
do_npm_cmd run build

popd

echo `date` Done. | tee -a log/build-ui.log
popd
