// Copyright (c) 2013 OpenM++
// This code is licensed under MIT license (see LICENSE.txt for details)

#include <cmath>
#include "om_types.h" // model-specific types
#include "omc/Agent.h"
#include "omc/AgentVar.h"
#include "omc/Event.h"

// The following macro is not defined for Modgen models.
// It can be used to exclude Modgen-specific C++ code during C++ compilation by openM++.
// Both the Modgen compiler and omc ignore preprocessor directives in model source code.
#define OPENM

#define TRUE true
#define FALSE false
#define WAIT( delta_time ) (time + (delta_time))

// The following are temporary kludges
#define WriteDebugLogEntry printf
#define GetCaseSample() 0
#define case_id 0

namespace openm {
    // run-time support functions

	double RandUniform(int strm);
}

// Functions generated by om compiler
extern void StartCase(int case_counter);
extern void EndCase();
extern bool DoNextEvent();

